[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pixel_engine"
authors = [{name = "Namit Singh", email = "namits@uw.edu"}]
dynamic = ["version", "description"]
